name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python3 --version
    - run: pip3 install -r bin/requirements.txt
    - run: python3 bin/lint.py a.tsv b.tsv c.tsv d.tsv e.tsv
