name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - run: pip install -r bin/requirements.txt
    - run: make --always-make
    - run: git diff --exit-code || (echo "::error::Files in dist/ out of sync. Run 'make' or let the repository maintainer do this." && false)
