name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - run: pip3 install python-chess
    - run: python3 bin/lint.py a.tsv b.tsv c.tsv d.tsv e.tsv
